- name: put a systemd unit file
  template: src=service.j2 dest=/etc/systemd/system/{{ systemd_service_name }}.service
  notify:
      - systemd start {{ systemd_service_name }}
      - systemd enable {{ systemd_service_name }}
      - systemd restart {{ systemd_service_name }}
  register: service_config

- name: enable {{ systemd_service_name }} service
  service: name={{ systemd_service_name }} enabled=yes state=started
  ignore_errors: True

- name: reload service config
  systemd: daemon_reload=yes
