---
- name: systemd restart {{ systemd_service_name }}
  service: name={{ systemd_service_name }} state=restarted

- name: systemd reload {{  systemd_service_name }}
  service: name={{ systemd_service_name }} state=reloaded

- name: systemd start {{ systemd_service_name }}
  service: name={{ systemd_service_name }} state=started

- name: systemd enable {{ systemd_service_name }}
  service: name={{ systemd_service_name }} enabled=yes
